/** Generate a reviewable, immutable account manifest from read-only SDK discovery. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PublicKey } from '@solana/web3.js';
import { getAssociatedTokenAddressSync } from '@solana/spl-token';
const source=process.env.EXPONENT_INSPECT_FILE;
if(!source) throw Error('EXPONENT_INSPECT_FILE must point to the read-only discovery JSON');
const s=JSON.parse(readFileSync(source,'utf8'));
const mints=['5Y8NV33Vv7WbnLfq3zBcKSdYPrk7g2KoiQoe7M2tcxp5','HH7FiYbEfDwQoK2ZJpkMz1T6wG6TqPsWcxWCtEVgigrZ','G1qbuP11CdquJCzuDjruWqatQAHroajmxhLfeQVgHosF','GFpXWuDCm7QMjkYbMveNZoLzybqJaginDDvuX3bJqgLF'];
const dynamic=[s.safe,...mints.map(m=>getAssociatedTokenAddressSync(new PublicKey(m),new PublicKey(s.safe),true).toBase58())];
const manifest:any={sdkVersion:'0.9.29',market:s.market,maturity:1799586000,coreVault:s.core.selfAddress,syMeta:s.generic.selfAddress,scope:s.generic.account.interfaceAccounts[0],scopeIndex:108,whirlpool:'7jhhyxPUKpu42hPGSYwgMXbR2dtVJHKhs8DW3sAAgAvX',lookupTables:[s.state.addressLookupTable,s.core.addressLookupTable],actions:{}};
let rust='// Immutable ONyc 10JAN27 accounts, reviewed against SDK 0.9.29 and on-chain state.\n// Generated by client/src/exponentTemplates.ts; dynamic roles: Safe=1, ONyc=2, PT=3, SY=4, YT=5.\nuse crate::exponent::Template;\nuse anchor_lang::prelude::*;\n';
for(const action of ['buy','sell','redeem']) {
 const ixs=s.instructions[action];
 if(ixs.length!==1) throw Error('Additional upstream instructions require review');
 const ix=ixs[0];
 const accounts=ix.keys.map((k:any)=>{const role=dynamic.indexOf(k.key)+1;if(k.signer&&role!==1)throw Error('Unexpected signer');return {role,key:role?'11111111111111111111111111111111':k.key,writable:k.writable,signer:k.signer}});
 manifest.actions[action]={program:ix.program,discriminator:ix.data.slice(0,2),syAccountsUntil:10,accounts};
 rust+=`pub const ${action.toUpperCase()}: [Template; ${accounts.length}] = [\n`+accounts.map((k:any)=>`    Template { role: ${k.role}, key: pubkey!("${k.key}"), writable: ${k.writable}, signer: ${k.signer} },`).join('\n')+'\n];\n';
}
const root=fileURLToPath(new URL('../../',import.meta.url));
writeFileSync(root+'web/src/lib/exponent-onyc-10jan27.json',JSON.stringify(manifest,null,2)+'\n');
writeFileSync(root+'programs/yield-vault/src/exponent_accounts.rs',rust);
console.log('Generated immutable manifest for',manifest.market);
